### ISSUE TITLE
Sky cover

### ISSUE THREAD

**Issue by pierrbt** [Mysterious-Developers/weather-widget#10]
**Is your feature request related to a problem? Please describe.**
We don't really understand what the sky cover raw means. SCT or OVC are not explicit enough

**Describe the solution you'd like**
You should assign each code with a adjective to describe better the sky cover

**Additional context**
You should use a switch() method to find which word to use

**Scrennshot**
![image](https://user-images.githubusercontent.com/83456236/180108638-abb813ab-928c-4358-97d1-9dd85c7c9b5e.png)

**Comment by denisbt** [comment]
For informations about clouds, you can use the following informations : 

SKC;Sky Clear;Aucun Nuage;
FEW;Few Clouds;Quelques Nuages;
SCT;Scattered;Nuages Epars;
BKN;Broken Clouds;Nuages Fragmentés;
OVC;Overcast Clouds;Ciel Couvert;
NSC;No Significant Clouds;Pas de Nuages Significatifs;
NCD;No Clouds Detected;Aucun Nuage;
CAVOK;Ceiling And Visibility OK;

**Comment by pierrbt** [comment]
> For informations about clouds, you can use the following informations :
> 
> SKC;Sky Clear;Aucun Nuage; FEW;Few Clouds;Quelques Nuages; SCT;Scattered;Nuages Epars; BKN;Broken Clouds;Nuages Fragmentés; OVC;Overcast Clouds;Ciel Couvert; NSC;No Significant Clouds;Pas de Nuages Significatifs; NCD;No Clouds Detected;Aucun Nuage; CAVOK;Ceiling And Visibility OK;

Thanks a lot for all these informations, I will integrate them in the next v1.8 release !

**Comment by pierrbt** [comment]
I made a map to convert the code into a number, is that correct ?
```cpp
skyCover["SKC"] = 0/8;
skyCover["FEW"] = 1/8;
skyCover["SCT"] = 3/8;
skyCover["BKN"] = 6/8;
skyCover["OVC"] = 8/8;
skyCover["NSC"] = 1/8;
skyCover["NCD"] = 0/8;
skyCover["CAVOK"] = 0/8;
```

**Comment by pierrbt** [comment]
I finished the code that convert the covering code into its definition, if you're curious, you can look at the code : 
```cpp
 // On créé un dictionnaire qui au code, renvoie la définition
      std::map<QString, QString> skyCover;
      skyCover["SKC"] = "Aucun Nuage (0/8)";
      skyCover["FEW"] = "Quelques Nuages (1/8)";
      skyCover["SCT"] = "Nuages Épars (3/8)";
      skyCover["BKN"] = "Nuages Fragmentés (6/8)";
      skyCover["OVC"] = "Ciel Couvert (8/8)";
      skyCover["NSC"] = "Pas de Nuages Significatifs (1/8)";
      skyCover["NCD"] = "Aucun Nuage (0/8)";
      skyCover["CAVOK"] = "Aucun Nuage, bonne visibilité (0/8)";

      // On cherche pour le code donné
      std::map<QString, QString>::iterator it = skyCover.find(infos[22]);
      if(it != skyCover.end()) // Si c'est trouvé, on met la définition
          cover->setText("Couverture : " + it->second);
      else
          cover->setText("Couverture : " + infos[22]); // Si ça ne trouve pas la définition, ça met le code
```
