### ISSUE TITLE
Station research

### ISSUE THREAD

**Issue by denisbt** [Mysterious-Developers/weather-widget#22]
Great job for this new release.
I can't find any station with IATA or OACI code ? It was possible in previous release and it's very useful. Do you plan to make it possible again ?

**Comment by pierrbt** [comment]
Great report ! I totally forgot to search the airport with the IATA or ICAO, the SQL request currently look like this :
```sql
SELECT icao,iata,name,country,latitude,longitude 
FROM airports 
WHERE name LIKE '%<cityName>%' OR city LIKE '%<cityName>%'"
```
I just have to ad if it's like the iata

**Comment by pierrbt** [comment]
I added that feature in the 2.1 release !
