### ISSUE TITLE
Raw informations

### ISSUE THREAD

**Issue by denisbt** [Mysterious-Developers/weather-widget#26]
Since last releases, raw informations are not availables. You need to fix that in a future release
![raw](https://user-images.githubusercontent.com/109612349/182634253-2315de6e-1bcd-452f-b11b-251af35d33b8.png)
.

**Comment by pierrbt** [comment]
Yes I have not updated that function, it should be fixed in the next release

**Comment by pierrbt** [comment]
I just removed it in release 2.4.
