### ISSUE TITLE
Special names

### ISSUE THREAD

**Issue by denisbt** [Mysterious-Developers/weather-widget#3]
Trying to find JFK, using new york as city name. It doesn't work

**Comment by pierrbt** [comment]
I'm working on it

**Comment by pierrbt** [comment]
I modified the bad parameters of the QCompleter, which was filtering the already filtered airports : it was only displaying the airports with the city name into them, so the JFK ( John F Kennedy International Airport ) aiport wasn't displayed. See the [new release](https://github.com/Mysterious-Developers/weather-widget/releases/tag/v1.5)
