### ISSUE TITLE
search with no matching data ?

### ISSUE THREAD

**Issue by denisbt** [Mysterious-Developers/weather-widget#4]
Trying to find "abc" in the town field. It returns CZL - ****.
Can you add a country information ?

**Comment by pierrbt** [comment]
Do you prefer that i add the coutry name on the "Station" raw or on the right of the town field @denisbt ?

**Comment by denisbt** [comment]
The best order should be :
- Country
- Town
- Station
-

In a future realase you can add a flag to switch between Englsih/French and Spanish tags

**Comment by pierrbt** [comment]
Ok, I changed the order of the informations, and I also added the ISO code of the coutry ( 2 letter code ). Finally, I added an hyperlink with the pinged airport on Google Maps !
You can see the [new release](https://github.com/Mysterious-Developers/weather-widget/releases/tag/v1.6)
