### ISSUE TITLE
Température

### ISSUE THREAD

**Issue by Martinltx** [Mysterious-Developers/weather-widget#7]
La température [s'affiche inconnu
![temp](https://user-images.githubusercontent.com/109704390/180101391-c8d181f0-d373-4687-9ea1-693bce5a6da8.png)

**Comment by pierrbt** [comment]
I really don't know why it do not find the temperature, I will make a better note when it isn't found. See you tomorrow

**Comment by pierrbt** [comment]
I changed the note of "Inconnu°C" by "N/A" (not available) but I actually don't know why the metars file don't contains the temperature of Toronto's airport, maybe they don't measure temperature, if someone know, it could be interesting.

Now, the app display that : 
![image](https://user-images.githubusercontent.com/83456236/180248799-2b6cc53a-57bf-424a-9d1e-4ee65e6cf045.png)

If you are curious, you can try to understand the line to display that : 
```cpp
// Si la temperature est connue, ça affiche la température avec °C, sinon ça affiche N/A
temp->setText("Température : " + ((infos[5] != "Inconnu") ? (infos[5] + "°C") : ("N/A")));
```
